### PR TITLE
Use meow and jstransformer-jstransformer

### PR DESCRIPTION
**Pull request by RobLoach**
Also brings in Boilerplate.

### CODE REVIEW

**Comment by RobLoach** [comment]
https://github.com/substack/minimist#minimist another option.

**Comment by tunnckoCore** [comment]
why?

**Comment by RobLoach** [comment]
> why?

Why bring in the Boilerplate? So that the meta information is easier to maintain.

**Comment by tunnckoCore** [comment]
can't remember for what was that "why" lol, nevermind

**Pull request merged**
